### ISSUE TITLE
If don't have rlang pre-installed, won't install grateful

### ISSUE THREAD

**Issue by befriendabacterium** [Pakillo/grateful#20]
Not sure if it's just on my machine, but because I didn't have rlang installed, I got the error:

Error: Failed to install 'grateful' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang

Installed rlang and then installation works.

**Comment by Pakillo** [comment]
Hi, 
Thanks for the report. I think that's not a problem with `grateful` but a more general problem when updating R packages (`rlang` in this case), e.g. see https://stackoverflow.com/questions/26570912/error-in-installation-a-r-package
