### ISSUE TITLE
avoid citing package collection and its contained packages at the same time

### ISSUE THREAD

**Issue by huizezhang-sherry** [Pakillo/grateful#25]
Very interesting package!  

Just wondering if it is possible to have a post-processing that removes the individual package citation once the collection is cited. For example, if `tidyverse` is cited, there's no need to cite `ggplot2` separately.  

This might be also applied to other package collections.

**Comment by Pakillo** [comment]
Thanks for the suggestion! 
It's now possible to cite individual packages or collapse all citations into a single 'tidyverse' citation. See 951deb2169a31a087089e23ba58db179d23ce99d
