### ISSUE TITLE
Fail to install 'unknown package' from GitHub

### ISSUE THREAD

**Issue by fgardavaud** [Pakillo/grateful#26]
Dear,
I fail to install this R package (in the last released of Rstudio with R4.1.1) whereas it's seems to be very helpful.
When I copy/paste the install command line `remotes::install_github("Pakillo/grateful")`, I have these errors in return :
`Erreur : Failed to install 'unknown package' from GitHub:
  error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number`

Someone could help me ?

**Comment by Pakillo** [comment]
Hi @fgardavaud 

sorry to hear you're having problems to install. It looks like a network connection issue though, not an error in the package.

Could you retry installing in a different computer or internet network? Can you install other packages hosted on github using remotes::install_github?

**Comment by fgardavaud** [comment]
Hi @Pakillo 
Thks for your reply. It works when I change my network configuration. It's weird because I don't have the same issue for other remote package. ??

**Comment by Pakillo** [comment]
Thanks. I don't know why it fails in this case. But good to know you managed to circumvent the issue. Happy citing!
