### ISSUE TITLE
prepare for CRAN

### ISSUE THREAD

**Issue by Pakillo** [Pakillo/grateful#27]
For CRAN submission:

https://r-pkgs.org/release.html

https://github.com/ThinkR-open/prepare-for-cran

https://github.com/tidyverse/multidplyr/issues/109

https://github.com/johnmackintosh/CRANt-touch-this

https://github.com/DavisVaughan/extrachecks

https://cran.r-project.org/web/packages/submission_checklist.html

https://cran.r-project.org/web/packages/policies.html

https://www.marinedatascience.co/blog/2020/01/09/checklist-for-r-package-re-submissions-on-cran/

**Comment by Bisaloo** [comment]
Hi @Pakillo, I use the grateful package in the [episoap R package](https://github.com/epiverse-trace/episoap), which provides Rmarkdown templates for common tasks in epidemiology and outbreaks analytics.

I believe your work is very useful and I'd love to see this package on CRAN. I understand you are likely busy with many other projects and I'd be happy to assist in any way if you'd like.

**Comment by Pakillo** [comment]
Hi @Bisaloo 

I've made a few changes to comply with CRAN. I've tested it thoroughly, but it'd be great if you could install the latest version from GitHub and check it works for you as well before resubmitting to CRAN

Thanks

**Comment by Bisaloo** [comment]
Hi @Pakillo,

Great to hear things are going well! I like the new change to comply with CRAN policies. I can confirm all is working perfectly for my use case after adding `out.dir = "."` to the `cite_packages()` call. :tada:

**Comment by Pakillo** [comment]
Great! Thanks for checking. Ready to resubmit then. Hope it gets through well and we can get {grateful} from CRAN very soon :)
