### ISSUE TITLE
restrictive R version dependency

### ISSUE THREAD

**Issue by goldingn** [Pakillo/grateful#3]
Depending on R versions >=3.4.1 seems kind of restrictive.

grateful won't install on my installation of R 3.4.0, but if I modify DESCRIPTION and rebuild, it seems to run just fine. Is there any reason you want to restrict to a recent version, or just that you haven't tested old versions?

**Comment by Pakillo** [comment]
Hi Nick!

Yeah that was automatic. I haven't tested earlier versions than 3.4.1, but there is nothing too fancy in the package that wouldn't work in former versions, I think.

What do you suggest to use? 3.4.0? I know a lot of people who still use 3.2 or even earlier... Is there any easy way to check the package against old versions, which doesn't require one to install all those old R versions?

**Comment by goldingn** [comment]
You could use `rhub::check_with_oldrel()` to check the package on whatever CRAN determines to be oldrel (`rversions::r_oldrel()` suggests it's 3.3.3) on a remote server.

You could also remove R from Depends altogether, if you reasonably expect it to work for all versions.

**Comment by Pakillo** [comment]
Thanks Nick. I have changed it to >= 3.0.0, as both checkpoint and rmarkdown (upon which this package depends) are supposed to work with any 3.* version. I will check later anyway
