### ISSUE TITLE
quarto supported?

### ISSUE THREAD

**Issue by ajpelu** [Pakillo/grateful#30]
Hi @Pakillo.
I love this pkg, and I use it a lot. Thanks. 

Recently I'm creating new projects with quarto documents, so I would like to continue using this amazing pkg. Are you planing to include an option to also scan .qmd documents?

**Comment by Pakillo** [comment]
Thanks @ajpelu 

I believe grateful already works with quarto documents, doesn't it? I just tried with a simple example. You can use it exactly as you did with Rmarkdown (see https://pakillo.github.io/grateful/#using-grateful-within-rmarkdown)

But please let us know if you still find problems

Best

**Comment by ajpelu** [comment]
Hi @Pakillo 
You are right!! 
I just checked that I was using an older version of the grateful package (beginner error).

I have tested now and it works perfectly. 

Thanks a lot!!

**Comment by ajpelu** [comment]
Hi @Pakillo
again with this issue.

When I use it in quarto, I need to put `#| results: asis` in the chunk to generate the correct way to write the references in paragraph way. For instance: 

```{r}
#| echo: false
#| results: asis
library(grateful)
grateful::cite_packages(output = "paragraph", out.dir = ".")
```
gives me the correct way. 
Maybe it's worthy to include some notes on the readme about that. 
Thanks again

**Comment by Pakillo** [comment]
Thanks Antonio

Do you have the most recent version of {grateful}? The need to specify `result: asis` was removed >1 year ago. Just checked the example Quarto document [here](https://github.com/Pakillo/grateful/blob/master/Rmd_Quarto/grateful-Quarto.qmd) and it worked.

But maybe there's something else going on. Please let me know after updating

Cheers

**Comment by Pakillo** [comment]
Perfect! Thanks for checking
