### ISSUE TITLE
Written paragraph is limited

### ISSUE THREAD

**Issue by jmclawson** [Pakillo/grateful#33]
In some circumstances, the included wording may not be ideal for the citation paragraph. (E.g., authorial “we” isn’t used in the humanities and some social sciences for a single-author paper.) 

In the long term, a templating system could be helpful. For the short term, a passive-voice option could add a lot of flexibility.

**Comment by Pakillo** [comment]
Thanks @jmclawson 

Yep, we realise users may want to change the paragraph wording, or remove some packages, or add more stuff. The idea is that the generated paragraph serves as a template that the user may modify afterwards. 

If using {grateful} to paste that paragraph in a document later, the user may modify at will. 

If using {grateful} with Rmarkdown or Quarto, I'd call cite_packages, render the document, then modify at will.

Note grateful will always generate BibTeX keys for all the packages, so you can cite them directly within Rmarkdown or Quarto as usual.

Given such flexibility, I'm hesitant to incorporate a templating system or too much further infrastructure at the moment. It's critical that grateful remains very simple and easy to use, and to maintain as well.

**Comment by jmclawson** [comment]
It’s understandable to focus on maintainability, so perhaps my issue and pull request really are outside the scope of a package primarily aimed for STEM citations. It’s just also *so very close* to providing the same usefulness in the humanities, where I do my research and teaching. 

Since the primary strength of RMarkdown and Quarto is in preparing reproducible reports (or working on documents in progress that will take many steps of review and revision), the paragraph output isn’t very handy if the document will then need to be modified each time it’s rendered. I’ll switch to using just the `grateful`-provided citation keys (for which I’m very grateful!) now that I understand that this limitation of the package is part of its design.

**Comment by jmclawson** [comment]
Humanities research sometimes uses first-person pronouns and sometimes uses passive voice to describe the methods, but it doesn't typically use plural pronouns for single-author works. Here's a table comparing Google results in one relevant journal (Digital Humanities Quarterly), in case the evidence is helpful: 

<table>
<tr>
<th>Google search</th><th># results</th>
</tr><tr>
<td>"we used" "dhq" site:digitalhumanities.org</td><td>378</td>
</tr><tr>
<td>"I used" "dhq" site:digitalhumanities.org</td><td>189</td>
</tr><tr>
<td>"was used" "dhq" site:digitalhumanities.org</td><td>527</td>
</tr>
</table>

**Comment by Pakillo** [comment]
Thanks @jmclawson 

That looks fine. Please give me a few days to review and integrate your pull request.

Best
