### ISSUE TITLE
Please do not test citations in other packages (at least not on CRAN)

### ISSUE THREAD

**Issue by yihui** [Pakillo/grateful#36]
Hi,

When I'm checking the reverse dependencies of **knitr**, I discovered that **grateful** had some tests that were too strict, e.g.,

https://github.com/Pakillo/grateful/blob/a0859f7256b21d6aa072b14b31316b55b10373db/tests/testthat/test-get_citations.R#L13
https://github.com/Pakillo/grateful/blob/a0859f7256b21d6aa072b14b31316b55b10373db/tests/testthat/test-utils_citations.R#L57-L88

These tests assume that the citations for **knitr** would never change, which is not true, e.g., next year `knitr2023` will become `knitr2024` and the test would be broken, or new books/papers about knitr could be written and there could be more citation entries in https://github.com/yihui/knitr/blob/master/inst/CITATION, etc.

I'll be grateful if these tests are either removed or skipped on CRAN, so that I can freely make changes in **knitr**'s citations in future without breaking **grateful**'s tests. Thank you!

**Comment by Pakillo** [comment]
Dear Yihui,

Apologies, and thanks for calling my attention to that. Fixed now.

P.S. I use your packages daily and they are fundamental to my work, so I'm forever grateful to you. Thanks
