### ISSUE TITLE
Cite base R by default

### ISSUE THREAD

**Issue by ivan-paleo** [Pakillo/grateful#37]
It would be nice to add an option to cite R itself when using the argument `pkgs`. A simple workaround is to add `"base"` to `pkgs` but this maybe could be done automatically...?

Example:
```
cite_packages(pkgs = c("grateful", "knitr"), output = "paragraph", out.dir = ".")
```
vs.
```
cite_packages(pkgs = c("grateful", "knitr", "base"), output = "paragraph", out.dir = ".")
```

**Comment by ivan-paleo** [comment]
That's true. Then what about mentioning explicitly in the help page to add "base" to `pkgs` in order to cite R? 
To be honest, I've always used `pkgs` and realized that the default (when not using that argument) was to cite R. That's why I think that adding one sentence in the help page might make it easier to find out.

**Comment by Pakillo** [comment]
Sure, I can certainly do that. Thanks for the suggestion!

**Comment by ivan-paleo** [comment]
Thank you for the great package!
