### ISSUE TITLE
grateful doesn't cite itself 

### ISSUE THREAD

**Issue by jkylearmstrong** [Pakillo/grateful#40]
Is there any way to add grateful so that it adds itself:

![image](https://github.com/Pakillo/grateful/assets/29757798/7f5a195a-f60f-4cd6-8b40-ec3b9b70514b)

**Comment by Pakillo** [comment]
Hi @jkylearmstrong 

Yes, {grateful} citation is omitted as default (argument `omit = c("grateful")`, see ?cite_packages()). 

Use `omit = NULL` to cite all packages, including {grateful}:

![image](https://github.com/Pakillo/grateful/assets/1597843/7acacc6a-638a-4c56-af0c-f49c33dc43f1)

**Comment by jkylearmstrong** [comment]
Awesome! I missed that in the documentation - just found out about this package - it's really neat. Thanks for putting it together! I just wanted to make sure that I cited you along with everyone else. :)

**Comment by Pakillo** [comment]
You' re welcome. Happy citing!
