### ISSUE TITLE
Package not found error

### ISSUE THREAD

**Issue by Coelhodeh** [Pakillo/grateful#43]
If there is only 1 unrecognized package, the program does not give any list?
In this case, do I have to transform all lines of code where the unrecognized package appears for grateful to run normally?

Thank you for the clarification!

**Comment by Pakillo** [comment]
Hi @Coelhodeh 

Thanks for trying grateful. You can omit that package using `cite_packages(omit = "pkgname")`, so that grateful will ignore that package (i.e. will not try to grab a citation for it).

I've updated the FAQ on this: https://pakillo.github.io/grateful/#error-there-is-no-package-called
