### ISSUE TITLE
some packages not generating citations

### ISSUE THREAD

**Issue by jkylearmstrong** [Pakillo/grateful#44]
Here is a reproducible example, some packages such as  `survival` or `future` are not generating citations. I'm not sure if the error is because they have multiple citations? I looked at `get_citation_and_citekey` and `add_citekey` both give outputs 

````
---
title: "example"
bibliography:
  - grateful-refs.bib
format: pdf
---

```{r}
library('survival')
library('future')
```

```{r}
grateful:::get_citation_and_citekey('survival')
```

```{r}
grateful:::add_citekey('survival', citation(package = "survival"))
```

```{r}
grateful::cite_packages(output = "paragraph",
                        out.dir = here::here(),
                        omit = NULL,
                        include.RStudio = F,
                        passive.voice = T)
```

```{r}
sessionInfo()
```
````
[example.pdf](https://github.com/user-attachments/files/15538446/example.pdf)

**Comment by Pakillo** [comment]
Hi @jkylearmstrong 

Thanks for the reprex. This in fact looks like a bug in how citation keys are parsed [here](https://github.com/Pakillo/grateful/blob/fbda5043dec2eb1efbb33a8185e51dafad32a82b/R/get_citations.R#L69). In particular, citation keys containing a '-' (like those for future 'RJ-2021-048' or survival package 'survival-package') are missed.

I think changing the regex to '{[\w-]+,$' could fix it, but need to make sure it works fine in all cases (comments/suggestions/alternatives welcome). I'll push a fix asap

Thanks!

**Comment by jkylearmstrong** [comment]
You would probably know better than I, my regex is horrible! :)

**Comment by Pakillo** [comment]
Should be fixed now (v 0.2.8). Please let me know if you still find problems. Thanks for reporting!

**Comment by jkylearmstrong** [comment]
@Pakillo - tested with the github version and it seems to work for the `survival` package. Thanks for putting this together! very helpful!

**Comment by Pakillo** [comment]
Great! Thanks for checking. Happy citing!
