### ISSUE TITLE
Some citations not rendering properly.

### ISSUE THREAD

**Issue by jkylearmstrong** [Pakillo/grateful#53]
Hi there, might be related to a previously reported issue [https://github.com/Pakillo/grateful/issues/44](https://github.com/Pakillo/grateful/issues/44) but some citations are again not rendering correctly, in particular, I notice that `future` is having issues again, but I don't think it's the exact same situation we were in last time. I am using `grateful` Version: 0.2.10 from CRAN. 

![image](https://github.com/user-attachments/assets/60235114-9be4-442e-9322-d5e003ca32b0)

**Comment by Pakillo** [comment]
Hi @jkylearmstrong,

Many thanks for reporting. I can't reproduce this problem (see example below). Can you check if those references (e.g. partykit2006) are saved in the BibTeX file (`grateful-refs.bib` by default)? It looks as if it can't find those references in the BibTeX file when rendering (but can find others). 

````
---
title: "example"
bibliography:
  - grateful-refs.bib
format: pdf
---

```{r}
library('survival')
library('future')
```

```{r}
grateful::cite_packages(output = "paragraph",
                        out.dir = here::here(),
                        passive.voice = TRUE)
```

```{r}
sessionInfo()
```
````

[test.pdf](https://github.com/user-attachments/files/17544966/test.pdf)

**Comment by jkylearmstrong** [comment]
Scratch, that, the mistake was mine. I had

```
grateful::cite_packages(output = "paragraph",
                        out.dir = here::here(),
                        omit = NULL,
                        include.RStudio = F,
                        passive.voice = T)
```

and unless the document is in the main directory of the RProject, the former will not work whereas, this will always print out relative to the document's rendering path:

```
grateful::cite_packages(output = "paragraph",
                        out.dir = getwd(),
                        omit = NULL,
                        include.RStudio = F,
                        passive.voice = T)
```

I just moved some files around and this didn't occur to me until I actually looked at the code. 

Thanks!

**Comment by Pakillo** [comment]
Ah yes, `getwd()` is [recommended](https://pakillo.github.io/grateful/reference/cite_packages.html#arg-out-dir) for `out.dir`. It was the default, but had to remove it to comply with CRAN policies. Thanks for the follow up, and glad it works!

Cheers
