### ISSUE TITLE
Integration with pacman

### ISSUE THREAD

**Issue by meenaparam** [Pakillo/grateful#7]
Really like the `grateful` package! But I've noticed it doesn't pick up packages that have been loaded via the `p_load` function in `pacman`. In the future, would you consider adding an extension to include packages in citations that have been loaded through `pacman`? There is a `p_citation` function in `pacman` that might be of use here, else perhaps a way to search for packages loaded via both standard `library` calls and via `p_load`?

More info on `pacman` here: https://cran.r-project.org/web/packages/pacman/pacman.pdf

Thanks for your consideration and keep up the good work!

**Comment by Pakillo** [comment]
Hi @meenaparam ,

Thanks for the suggestion, and sorry for the delay. `grateful` now uses `renv` for scanning dependencies, so it should also detect packages loaded via `pacman`.

Hope it is still useful to you and others

Cheers
