### ISSUE TITLE
Error in FUN(X[[i]], ...) : package ‘AED’ not found

### ISSUE THREAD

**Issue by prosoitos** [Pakillo/grateful#9]
It seems that `grateful` relies on `AED` which has been discontinued.

**Comment by Pakillo** [comment]
Thanks for trying grateful. Do you get that error when installing the package, or when running `cite_packages`? 
`grateful` does not depend on `AED`. Only on `checkpoint`, `rmarkdown` and `utils`. 

Is it possible that you are calling `library(AED)` somewhere in your scripts, but the package is not installed in your system? `grateful` assumes all the packages called in scripts are actually installed, and then retrieves citation information for each. It looks like it cannot find the package in this case. I could reproduce that error. Try installing the package, or commenting it out in your script, and please let me know how it goes

**Comment by prosoitos** [comment]
I get the message when running `cite_packages()` (I had no problem to install).

I am not calling `AED` myself. I even did a test: create a script with only code:
```
library(grateful)

cite_packages()
```
And that is enough to get the error message.

Of note, I am running R in emacs ESS. If you don't have the problem, it must be something in my settings, but I have never heard of `AED` before and never run into such issue. Unless, maybe, your package only runs in RStudio because it is using `AED` in the background through RStudio???

**Comment by Pakillo** [comment]
Thanks for the info. Sorry I don't use emacs so I have never tried grateful there. But I hope to make it work.

I think AED may refer to [this package](https://github.com/romunov/AED) which has never been on CRAN. I don't think Rstudio is calling AED at all. Most likely, cite_packages is finding too many packages (including AED) when searching in your computer. At least that's what happened to me when running cite_packages outside Rstudio.

As cite_packages search for all packages called in scripts within your working directory, please try first setting your working directory to some folder with a simple R script, then calling cite_packages:
```
setwd("C:/myproject")
cite_packages()
```

This worked for me. But then we must be able to run pandoc through rmarkdown. I think this has to be revised for people not working with Rstudio. I'll try to have a look at it next week.

**Comment by prosoitos** [comment]
Right. This time it works, except that, of course, it does not find `pandoc` (as you said) and I get the error message that you probably got:

```
> cite_packages()


processing file: refs.Rmd
  |.................................................................| 100%
  ordinary text without R code


output file: refs.knit.md

/usr/bin/pandoc +RTS -K512m -RTS refs.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output /home/data/adm/citations.html --email-obfuscation none --self-contained --standalone --section-divs --template /usr/lib/R/library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /tmp/RtmpgG0HY3/rmarkdown-str51ea63593507.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --filter pandoc-citeproc 
Error running filter pandoc-citeproc:
Could not find executable pandoc-citeproc
Error: pandoc document conversion failed with error 83
```
But this is quite unpractical anyway as I obviously need to work in my projects and not some empty place.

Thanks for checking this out and let me know if you find solutions. And thanks for your time and your package.
